name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Only run on code changes
    paths:
      - "apps/**/*.ts"
      - "apps/**/*.tsx"
      - "apps/**/*.js"
      - "apps/**/*.jsx"
      - "packages/**/*.ts"
      - "packages/**/*.tsx"
      - "packages/**/*.js"
      - "packages/**/*.jsx"
      - "*.json"
      - "*.md"
      - ".github/workflows/*.yml"

jobs:
  claude-review:
    # Skip review for draft PRs, WIP, or explicit skip-review tags
    # Also skip for first-time contributors (security)
    if: |
      !github.event.pull_request.draft &&
      !contains(github.event.pull_request.title, '[WIP]') &&
      !contains(github.event.pull_request.title, '[skip-review]') &&
      (github.event.pull_request.author_association != 'FIRST_TIME_CONTRIBUTOR' &&
       github.event.pull_request.author_association != 'FIRST_TIMER')

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Changed to write for sticky comments
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # All Claude CLI arguments including model, max-turns, and allowed tools
          claude_args: |
            --model claude-sonnet-4-20250514
            --max-turns 30
            --allowedTools "Read(apps/**)" "Read(packages/**)" "Read(_docs/**)" "Read(*.json)" "mcp__github_ci__get_ci_status" "mcp__github_ci__get_ci_status" "mcp__github_comment__update_claude_comment"
            
          # Enable sticky comments to update same comment on subsequent pushes
          use_sticky_comment: true

          # Chrome Extension specific review prompt
          prompt: |
            Review this Chrome Extension PR focusing on:
  
            **High-Impact Issues:**
            - Security vulnerabilities (XSS, CSP, API exposure)
            - Chrome Extension compliance (manifest, permissions)
            - Logic errors and edge cases
            - Architecture and performance issues
            - Breaking changes
            
            **Assume lint/typecheck passed locally.** 
            Focus on issues static analysis tools can't catch.
            Be concise but thorough.
