name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Only run on code changes
    paths:
      - "apps/**/*.ts"
      - "apps/**/*.tsx"
      - "apps/**/*.js"
      - "apps/**/*.jsx"
      - "packages/**/*.ts"
      - "packages/**/*.tsx"
      - "packages/**/*.js"
      - "packages/**/*.jsx"
      - "*.json"
      - "*.md"
      - ".github/workflows/*.yml"

jobs:
  claude-review:
    # Skip review for draft PRs, WIP, or explicit skip-review tags
    # Also skip for first-time contributors (security)
    if: |
      !github.event.pull_request.draft &&
      !contains(github.event.pull_request.title, '[WIP]') &&
      !contains(github.event.pull_request.title, '[skip-review]') &&
      (github.event.pull_request.author_association != 'FIRST_TIME_CONTRIBUTOR' &&
       github.event.pull_request.author_association != 'FIRST_TIMER')

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Changed to write for sticky comments
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        continue-on-error: true
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # All Claude CLI arguments including model, max-turns, and allowed tools
          claude_args: |
            --model claude-sonnet-4-20250514
            --max-turns 20
            --allowedTools "Bash(npm run lint)" "Bash(npm run typecheck)" "Bash(npm run test)" "Bash(npm run)" "Read(packages/**)" "Read(apps/**)" "Read(_docs/**)" "Read(*.md)" "Read(package.json)" "Read(tsconfig.json)" "mcp__github_ci__get_ci_status"

          # Enable sticky comments to update same comment on subsequent pushes
          use_sticky_comment: true

          # Chrome Extension specific review prompt
          prompt: |
            Review this Chrome Extension pull request. Keep your review concise and actionable.

            Focus on critical issues only:
            1. Security vulnerabilities (API keys, XSS, CSP violations)
            2. Chrome Extension manifest/permissions issues
            3. Breaking changes or bugs
            4. Type safety violations
            5. Missing error handling

            Skip minor style issues unless they impact functionality.
            Reference specific line numbers.
            Provide code suggestions for any issues found.
