name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Set model, max turns, and allowed tools via claude_args
          claude_args: |
            --model claude-sonnet-4-1-20250805
            --max-turns 15
            --allowed-tools "Bash(npm install)" "Bash(npm run build)" "Bash(npm run test)" "Bash(npm run lint)" "Bash(npm run typecheck)" "Bash(npm run format:fix)" "Read(packages/**)" "Read(apps/**)" "Read(_docs/**)" "Read(*.md)" "Read(*.json)" "Read(tsconfig.json)" "Read(.github/**)" "Write" "Edit" "MultiEdit"

          # Concise instructions for interactive assistance
          prompt: |
            You're helping with Briefcase, a Chrome Extension (MV3) project.
            - Check CLAUDE.md for project conventions
            - Follow TypeScript/React best practices
            - Run lint and typecheck after changes
            - Provide concise, actionable responses
            - Focus on solving the specific request
